### ISSUE TITLE
Addon should not import Qt at Startup to allow for import on any system

### ISSUE THREAD

**Issue by Lypsolon** [ynput/ayon-usd#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

The add-on imports Qt at startup and thereby needs Qt to be available on import. 
Some systems don't have Qt available, but they might want to use other functions from the add-on. 

### How would you imagine the implementation of the feature?

- [ ] Should we move the parts that need Qt with all their functions to a different file and import them in the function call of the Addon Class? 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by BigRoy** [comment]
As far as I know this has been resolved - right @Lypsolon ?

The import is now only here on `tray start`: https://github.com/ynput/ayon-usd/blob/227d5ef255be601cbbd2e8e1a8eb6754254b8298/client/ayon_usd/addon.py#L126

**Comment by Lypsolon** [comment]
> As far as I know this has been resolved - right @Lypsolon ?
> 
> The import is now only here on `tray start`:
> 
> https://github.com/ynput/ayon-usd/blob/227d5ef255be601cbbd2e8e1a8eb6754254b8298/client/ayon_usd/addon.py#L126

yes this is correct. 
the import is at try start now. 

we still have the question about downloading usd on the farm but i believe this has no priority.

**Comment by BigRoy** [comment]
> we still have the question about downloading usd on the farm but i believe this has no priority.

Great - sounds like a separate issue. If that's not tracked anywhere, could you create an issue for it?
